transportation/transport/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('lines/', views.LinesView.as_view(), name="lines"),
    path('lines/new/', views.CreateLineView.as_view(), name="create_line"),
    path('lines/<pk>/update', views.UpdateLineView.as_view(), name="update_line"),
    path('lines/<pk>/delete', views.DeleteLineView.as_view(), name="delete_line"),
    path('stations/', views.StationsView.as_view(), name="stations"),
    path('stations/new/', views.CreateStationView.as_view(), name="create_station"),
    path('stations/<pk>/delete', views.DeleteStationView.as_view(), name="delete_station"),
    path('stations/<pk>/update', views.UpdateStationView.as_view(), name="update_station"),
    path('stops/', views.StopsView.as_view(), name="stops"),
    path('stops/new/', views.CreateStopView.as_view(), name="create_stop"),
    path('stops/<pk>/delete', views.DeleteStopView.as_view(), name="delete_stop"),
    path('stops/<pk>/update', views.UpdateStopView.as_view(), name="update_stop"),


]

transportation/transportation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transport.urls'))
]

transportation/transport/models.py
from django.db import models

# Create your models here.
class Line(models.Model):
    name = models.CharField(unique=True, max_length=200)

    def get_absolute_url(self):
        return "/lines"

    def __str__(self):
        return f"{self.name}"

class Station(models.Model):
  name = models.CharField(unique=True, max_length=200)
  accessible = models.BooleanField(default=False)

  def get_absolute_url(self):
    return "/stations"

  def __str__(self):
    return f"{self.name}{' (♿)' if self.accessible else ''}"

class Stop(models.Model):

    class Meta:
        unique_together = (('line', 'stop_number'))

    def get_absolute_url(self):
            return "/stops"

    line = models.ForeignKey(Line, on_delete=models.CASCADE)
    station = models.ForeignKey(Station, on_delete=models.CASCADE)
    stop_number = models.PositiveIntegerField()

    def __str__(self):
            return f"{self.line.name} -- {self.station.name} [{self.stop_number}]"

transportation/transport/forms.py
from django import forms
from .models import Line, Station, Stop



class LineForm(forms.ModelForm):
  class Meta:
    model = Line
    fields = "__all__"


class StationForm(forms.ModelForm):
  class Meta:
    model = Station
    fields = "__all__"


class StopForm(forms.ModelForm):
  class Meta:
    model = Stop
    fields = "__all__"

transportation/transport/views.py
from django.shortcuts import render
from .models import Line, Stop, Station
from .forms import LineForm, StationForm, StopForm
from django.views.generic import TemplateView, ListView,CreateView, DeleteView, UpdateView
# Create your views here.
class HomeView(TemplateView):
    template_name = "transport/home.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["lines"] = Line.objects.all()
        context["stations"] = Station.objects.all()
        context["stops"] = Stop.objects.all()
        return context


class LinesView(ListView):
    template_name = "transport/lines.html"
    model= Line

class CreateLineView(CreateView):
    template_name = "transport/add_line.html"
    form_class = LineForm
    model = Line

class DeleteLineView(DeleteView):
    template_name = "transport/delete_line.html"
    success_url = "/lines/"
    model = Line

class UpdateLineView(UpdateView):
    template_name = "transport/update_line.html"
    model = Line
    form_class = LineForm

class StationsView(ListView):
    template_name = "transport/stations.html"
    model = Station

class CreateStationView(CreateView):
    template_name = "transport/add_station.html"
    form_class = StationForm
    model = Station

class DeleteStationView(DeleteView):
    template_name = "transport/delete_station.html"
    model = Station
    success_url = "/stations/"

class UpdateStationView(UpdateView):
    template_name = "transport/update_station.html"
    model = Station
    form_class = StationForm

class StopsView(ListView):
    template_name = "transport/stops.html"
    model= Stop


class CreateStopView(CreateView):
    template_name = "transport/add_stop.html"
    form_class = StopForm
    model = Stop

class DeleteStopView(DeleteView):
    template_name = "transport/delete_stop.html"
    model = Stop
    success_url = "/stops/"


class UpdateStopView(UpdateView):
    template_name = "transport/update_stop.html"
    model = Stop
    form_class = StopForm

transportation/transport/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="{% static 'transport/style.css' %}"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Oxygen:wght@300;400;700&display=swap"
      rel="stylesheet"/>
        <title>
         Transport Information
        </title>
    </head>
    <body>
        <div class="app">
           <header>
               <div class="header-first-row">
                   <h1 class="title">Transportation Information</h1>
               </div>
               <nav class="navbar">
                   <a class="nav-item" href="{% url 'home' %}">Home</a>
                   <a class="nav-item" href="{% url 'lines' %}">Lines</a>
                   <a class="nav-item" href="{% url 'stations' %}">Stations</a>
                    <a class="nav-item" href="{% url 'stops' %}">Stops</a>
               </nav>
           </header>
            <main>{% block content %}{% endblock %}</main>
        </div>
    </body>
</html>

transportation/transport/templates/transport/add_line.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Add a New Transport Line</h2>
<form method="post">
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

transportation/transport/templates/transport/add_station.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Add a New Transport Station</h2>
<form method="post">
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

transportation/transport/templates/transport/add_stop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Add a New Transport Stop</h2>
<form method="post">
  <div>
    {{ form.as_p }}
    <input type="submit" value="Submit" />
  </div>
</form>
{% endblock %}

transportation/transport/templates/transport/delete_line.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Delete Line</h2>
<form method="post">
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

transportation/transport/templates/transport/delete_station.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Delete Station</h2>
<form method="post">
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

transportation/transport/templates/transport/delete_stop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Delete Stop</h2>
<form method="post">
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm" />
</form>
{% endblock %}

transportation/transport/templates/transport/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Transport Information{% endblock %}
{% block content %}
<div class="home">
  <div>
    <h2>Lines</h2>
    <table class="line-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Stops</th>
        </tr>
      </thead>
      <tbody>
        {% for line in lines %}
        <tr>
          <td>{{ line.name }}</td>
          <td>
            <ul>
              {% for stop in line.stop_set.all %}
              <li>{{ stop.stop_number }}</li>
              <div>
                {{ stop.station.name }}{% if stop.station.accessible %} ♿ {% endif %}
              </div>
              {% endfor %}
            </ul>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

transportation/transport/templates/transport/lines.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <h2>Lines</h2>
    <table class="line-table">
        <thead>
            <tr>
                <th>Name</th>
                 <th>Stops</th>
                 <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for line in object_list %}
            <tr>
                <td>
                    <a href="{% url 'update_line' line.id %}">{{line.name}}</a>
                </td>
                <td>
                    <ul>
                        {% for stop in line.stop_set.all %}
                        <li>{{stop.stop_number}}</li>
                        <div>{{stop.station.name}}{% if stop.station.accessible %} ♿ {% endif %}</div>
                        {% endfor %}
                    </ul>
                </td>
                <td>
                    <a href="{% url 'delete_line' line.id %}" style="text-decoration: none; color: inherit;">❌</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'create_line' %}" style="display: inherit; text-align: center;
    border-radius: 15px; text-decoration: none;
    color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
</div>
{% endblock %}

transportation/transport/templates/transport/stations.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Transportation Information{% endblock %}
{% block content %}
<div>
  <h2>Stations</h2>
  <table class="line-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>On Lines</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
    {% for station in object_list %}
        <tr>
          <td>
            <a href="{% url 'update_station' station.id %}">{{ station.name }}</a>
            {% if station.accessible %}<span>  ♿️ </span>{% endif %}
          </td>
          <td>
            {% for stop in station.stop_set.all %}{{stop.line.name}}, {% endfor %}
          </td>
          <td><a href="{% url 'delete_station' station.id %}" style="text-decoration: none; color: inherit;">❌</a></td>
        </tr>
    {% endfor %}
    </tbody>
  </table>
  <a href="{% url 'create_station' %}" style="display: inherit; text-align: center; border-radius: 15px; text-decoration: none; color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
</div>
{% endblock %}

transportation/transport/templates/transport/stops.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Django Djitney{% endblock %}
{% block content %}
  <div>
    <h2>Stops</h2>
    <table class="line-table">
      <thead>
        <tr>
          <th>Line</th>
          <th>Stop Number</th>
          <th>Station</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      {% for stop in object_list %}
        <tr>
          <td>{{ stop.line.name }}</td>
          <td><a href="{% url "update_stop" stop.id %}">{{ stop.stop_number }}</a></td>
          <td>{{ stop.station.name }}</td>
          <td><a href="{% url "delete_stop" stop.id %}" style="text-decoration: none; color: inherit;">❌</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <a href="{% url "create_stop" %}" style="display: inherit; text-align: center; border-radius: 15px; text-decoration: none; color: inherit; padding: 4px; background-color: lightgreen;">➕</a>
  </div>
{% endblock %}

transportation/transport/templates/transport/update_line.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Update Line</h2>
<form method="post">
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

transportation/transport/templates/transport/update_station.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Update Station</h2>
<form method="post">
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}

transportation/transport/templates/transport/update_stop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Update Stop</h2>
<form method="post">
  {{ form }}
  <input type="submit" value="Update" />
</form>
{% endblock %}